# Generated by Django 2.0.1 on 2018-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, nunc eleifend diam porta, amet elit, nullam et, praesent luctus lacus egestas, vehicula sit. Urna sed porttitor malesuada sit quis venenatis, est morbi est fusce, lorem aliquet pede, sodales justo vel diam sit, nunc ultrices maecenas urna. Phasellus volutpat a orci, wisi consectetuer. Turpis et vitae. Maecenas a. Amet ridiculus suspendisse sociis nunc tortor, wisi a justo nullam, mauris lorem turpis et. Ut pede quisque vestibulum, fusce wisi ac tellus, ut adipiscing integer eget purus lobortis. Lobortis eu, nec consequat quis sed vestibulum eleifend elementum, aptent eu rutrum non vel, dui fusce vehicula senectus magna tempor, lectus nulla.')),
                ('typeOf', models.CharField(choices=[('Electronics', 'Electronics'), ('Sport', 'Sport'), ('Book', 'Book'), ('Clothing', 'Clothing')], default='None', max_length=20)),
            ],
        ),
    ]
