# Generated by Django 2.0.1 on 2018-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_incart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incart',
            name='product',
        ),
        migrations.AddField(
            model_name='incart',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
