# Generated by Django 2.0.1 on 2018-04-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180415_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='incart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
